openapi: 3.0.0
servers:
  - url: 'http://ufm.nvidia'
info:
  title: UFM REST API
  version: 1.0.0
tags:
  - name: events_management                                                                                         
    description: events management
paths:
  /ufmRest/app/events/external_event:                                                                               
    post:
      summary: Trigger external event
      tags:                                                                                                             
        - events_management
      description: Trigger an external event in UFM
      operationId: publishEvent                                                                                       
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event_id:
                  type: integer
                  description: Unique identifier for the event
                external_event_name:
                  type: string
                  description: Name of the external event
                external_event_type:
                  type: string
                  description: Type of the external event
                external_event_source:
                  type: string
                  description: Source of the external event
                description:
                  type: string
                  description: Description of the external event
              required:
                - event_id
                - external_event_name
                - external_event_type
                - external_event_source
                - description
      responses:
        '200':
          description: OK - The request was successful.
        '404':
          description: NOT FOUND - Event was not found (by ID).  